import { test as base, expect } from '@playwright/test';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomBytes } from 'node:crypto';
import { createApp } from '../server/app.js';

const test=base.extend({
 service:async({},use)=>{const dir=mkdtempSync(join(tmpdir(),'fleetops-browser-')),s=createApp({filename:join(dir,'app.sqlite')});const server=s.app.listen(0,'127.0.0.1');await new Promise(resolve=>server.once('listening',resolve));await use({url:`http://127.0.0.1:${server.address().port}`,db:s.db,password:randomBytes(20).toString('base64url')});await new Promise(resolve=>server.close(resolve));s.db.close();rmSync(dir,{recursive:true,force:true});}
});
async function setup(page,s){await page.goto(s.url);await expect(page.getByRole('heading',{name:'创建企业工作空间'})).toBeVisible();await page.getByLabel('工作空间名称').fill('测试企业车队');await page.getByLabel('管理员姓名').fill('测试管理员');await page.getByLabel('工作邮箱').fill('admin@example.test');await page.getByLabel('密码',{exact:true}).fill(s.password);await page.getByRole('button',{name:'创建工作空间'}).click();await expect(page.getByRole('heading',{name:'异常概览',exact:true})).toBeVisible();}
async function vehicle(page){await page.locator('.sidebar').getByRole('button',{name:'车辆档案'}).click();await page.getByRole('button',{name:'添加车辆',exact:true}).first().click();await page.getByLabel('车辆编号').fill('TEST-001');await page.getByLabel('所属运营组').fill('测试运营组');await page.getByLabel('车型',{exact:true}).fill('测试车型');await page.getByRole('button',{name:'保存',exact:true}).click();await expect(page.getByRole('heading',{name:'TEST-001',exact:true})).toBeVisible();}
async function incident(page){await page.locator('.sidebar').getByRole('button',{name:'异常概览'}).click();await page.getByRole('button',{name:'新增异常'}).click();await page.getByLabel('异常车辆').selectOption({label:'TEST-001 · 测试运营组'});await page.getByLabel('异常分类',{exact:true}).selectOption('temperature');await page.getByLabel('风险等级',{exact:true}).selectOption('高风险');await page.getByLabel('异常描述').fill('测试检查发现电池温度偏高，请安排诊断。');await page.getByText('补充监测指标（可选）').click();await page.getByLabel('指标名称').fill('电池温度');await page.getByLabel('发现时读数').fill('62');await page.getByLabel('单位',{exact:true}).fill('°C');await page.getByLabel('正常区间',{exact:true}).fill('20–45');await page.getByRole('button',{name:'创建事件',exact:true}).click();await expect(page.getByRole('heading',{name:'电池温度异常',exact:true})).toBeVisible();}
test('初始化、登记、卡片加载、蛇形四步与数量同步',async({page,service},info)=>{
 const errors=[];page.on('pageerror',error=>errors.push(error.message));
 await setup(page,service);await expect(page.locator('.anomaly-card')).toHaveCount(6);await expect(page.locator('.workspace')).toContainText('测试企业车队');await vehicle(page);await incident(page);
 await page.locator('.sidebar').getByRole('button',{name:'异常概览'}).click();
 await page.route('**/api/incidents/*',async route=>{await new Promise(resolve=>setTimeout(resolve,400));await route.continue();});
 await page.locator('.anomaly-card').filter({hasText:'电池温度异常'}).locator('.category-icon').click();await expect(page.getByText('正在加载事件与诊断快照…')).toBeVisible();await expect(page.locator('.snake-flow')).toBeVisible();await page.unroute('**/api/incidents/*');
 await expect(page.getByRole('heading',{name:/可能原因/})).toBeVisible();await expect(page.getByRole('heading',{name:/诊断结果/})).toBeVisible();await expect(page.getByRole('heading',{name:'事件时间线',exact:true})).toBeVisible();
 expect(await page.locator('.flow-node h3').allTextContents()).toEqual(['问题发现','原因分析','结果确认','处理执行']);
 const boxes=await Promise.all([0,1,3,2].map(i=>page.locator(`[data-step="${i}"]`).boundingBox()));expect(boxes[0].y).toBeCloseTo(boxes[1].y,0);expect(boxes[2].y).toBeCloseTo(boxes[3].y,0);expect(boxes[2].y).toBeGreaterThan(boxes[0].y);expect(boxes[2].x).toBeLessThan(boxes[3].x);
 await page.getByRole('button',{name:'受理并分析',exact:true}).click();await page.getByLabel('处理负责人').selectOption({label:'测试管理员'});await page.getByLabel('受理说明').fill('已确认异常，安排负责人进行诊断。');await page.getByRole('button',{name:'提交并继续'}).click();await expect(page.locator('.workflow-current b')).toHaveText('当前：原因分析');
 await page.getByRole('button',{name:'确认原因',exact:true}).click();await page.getByLabel('可能原因').fill('测试检查发现冷却回路堵塞。');await page.getByLabel('诊断结果').fill('测试确认冷却循环不足导致温度升高。');await page.getByLabel('处理方案',{exact:true}).fill('清理冷却回路并连续复测。');await page.getByLabel('分析补充说明').fill('完成现场检查，诊断结果已经确认。');await page.getByRole('button',{name:'提交并继续'}).click();await expect(page.locator('.workflow-current b')).toHaveText('当前：处理执行');
 await page.getByRole('button',{name:'提交处理结果',exact:true}).click();await page.getByLabel('处理后读数（°C）').fill('38');await page.getByLabel('处理结果说明').fill('已完成清理，复测温度保持正常。');await page.getByRole('button',{name:'提交并继续'}).click();await expect(page.locator('.workflow-current b')).toHaveText('当前：结果确认');
 await page.getByRole('button',{name:'确认并归档',exact:true}).click();await page.getByLabel('归档说明').fill('已核验所有记录与处理结果，确认归档。');await page.getByRole('button',{name:'确认并归档',exact:true}).last().click();await expect(page.locator('#form-error')).toContainText('请核验');await page.getByLabel('已核验实际处理结果').check();await page.getByRole('button',{name:'确认并归档',exact:true}).last().click();await expect(page.locator('.workflow-current b')).toHaveText('本次异常已闭环');await expect(page.locator('.flow-node.done')).toHaveCount(4);
 await page.screenshot({path:info.outputPath('detail.png'),fullPage:true});await page.locator('.sidebar').getByRole('button',{name:'异常概览'}).click();const card=page.locator('.anomaly-card').filter({hasText:'电池温度异常'});await expect(card.locator('.card-number strong')).toHaveText('1');await expect(card.locator('.card-status button').nth(0).locator('b')).toHaveText('0');await expect(card.locator('.card-status button').nth(2).locator('b')).toHaveText('1');await expect(page.locator('.stat-card').nth(2).locator('.stat-value')).toHaveText('1项');await page.reload();await expect(card.locator('.card-status button').nth(2).locator('b')).toHaveText('1');await page.screenshot({path:info.outputPath('home.png'),fullPage:true});expect(errors).toEqual([]);
});
test('多人读取、只读权限、服务器数据跨浏览器可见',async({page,browser,service})=>{
 await setup(page,service);await vehicle(page);await incident(page);await page.locator('.sidebar').getByRole('button',{name:'设置中心'}).click();await page.getByRole('button',{name:'团队成员'}).click();await page.getByRole('button',{name:'添加成员'}).click();
 const password=randomBytes(20).toString('base64url');await page.getByLabel('姓名',{exact:true}).fill('测试只读人员');await page.getByLabel('工作邮箱').fill('viewer@example.test');await page.getByLabel('初始密码').fill(password);await page.getByLabel('权限角色').selectOption('viewer');await page.getByRole('button',{name:'创建成员'}).click();await expect(page.getByText('测试只读人员',{exact:true})).toBeVisible();
 const context=await browser.newContext(),other=await context.newPage();await other.goto(service.url);await other.getByLabel('工作邮箱').fill('viewer@example.test');await other.getByLabel('密码',{exact:true}).fill(password);await other.getByRole('button',{name:'登录',exact:true}).click();await expect(other.locator('.anomaly-card').filter({hasText:'电池温度异常'}).locator('.card-number strong')).toHaveText('1');await expect(other.getByRole('button',{name:'新增异常'})).toHaveCount(0);await other.locator('.anomaly-card').filter({hasText:'电池温度异常'}).locator('.category-icon').click();await expect(other.locator('.snake-flow')).toBeVisible();await expect(other.getByRole('button',{name:'继续处理'})).toHaveCount(0);await context.close();
});
test('网络保存失败保留输入，恢复后可提交',async({page,service})=>{
 await setup(page,service);await vehicle(page);await incident(page);await page.getByRole('button',{name:'受理并分析'}).click();await page.getByLabel('处理负责人').selectOption({label:'测试管理员'});await page.getByLabel('受理说明').fill('该说明在断网后应该保留。');await page.route('**/api/incidents/*/advance',route=>route.abort());await page.getByRole('button',{name:'提交并继续'}).click();await expect(page.locator('#form-error')).toContainText('无法连接服务器');await expect(page.getByLabel('受理说明')).toHaveValue('该说明在断网后应该保留。');await page.unroute('**/api/incidents/*/advance');await page.getByRole('button',{name:'提交并继续'}).click();await expect(page.locator('.workflow-current b')).toHaveText('当前：原因分析');
});
test('搜索筛选、CSV 校验与不执行用户 HTML',async({page,service})=>{
 await setup(page,service);await vehicle(page);await incident(page);await page.locator('.sidebar').getByRole('button',{name:'异常概览'}).click();await page.getByLabel('搜索异常类型或车辆编号').fill('不匹配');await expect(page.getByRole('heading',{name:'没有找到匹配的异常'})).toBeVisible();await page.getByRole('button',{name:'重置筛选'}).click();await page.getByRole('button',{name:'导入',exact:true}).click();
 const csv='车辆编号,异常分类,风险等级,异常描述\nTEST-001,动力系统异常,中风险,"<img src=x onerror=window.injected=1>测试异常描述"';await page.locator('#csv-file').setInputFiles({name:'test.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});await expect(page.locator('#import-preview')).toContainText('格式校验通过');await page.getByRole('button',{name:'确认导入'}).click();await expect(page.locator('.anomaly-card').filter({hasText:'动力系统异常'}).locator('.card-number strong')).toHaveText('1');await page.locator('.anomaly-card').filter({hasText:'动力系统异常'}).locator('.category-icon').click();await expect(page.locator('.incident-description')).toContainText('<img src=x');expect(await page.evaluate(()=>window.injected)).toBeUndefined();
});
test('退出后重新登录保留服务器记录',async({page,service})=>{
  await setup(page,service);await vehicle(page);
  await page.locator('.sidebar').getByRole('button',{name:'设置中心'}).click();await page.getByRole('button',{name:'退出登录',exact:true}).click();
  await expect(page.getByRole('heading',{name:'登录工作空间'})).toBeVisible();await page.getByLabel('工作邮箱').fill('admin@example.test');await page.getByLabel('密码',{exact:true}).fill(service.password);await page.getByRole('button',{name:'登录',exact:true}).click();
  await expect(page.getByRole('heading',{name:'设置中心',exact:true})).toBeVisible();await page.locator('.sidebar').getByRole('button',{name:'车辆档案'}).click();await expect(page.getByRole('heading',{name:'TEST-001',exact:true})).toBeVisible();
});
test('同时更新的冲突保留说明并允许核对后提交',async({page,service})=>{
  await setup(page,service);await vehicle(page);await incident(page);
  await page.getByRole('button',{name:'受理并分析'}).click();await page.getByLabel('处理负责人').selectOption({label:'测试管理员'});await page.getByLabel('受理说明').fill('本人编辑的受理说明应当保留。');
  const data=await (await page.request.get(service.url+'/api/bootstrap')).json(),d=data.incidents[0];
  const response=await page.request.post(`${service.url}/api/incidents/${d.id}/comments`,{headers:{'X-CSRF-Token':data.csrf},data:{note:'另一会话新增补充记录并更新版本。'}});expect(response.status()).toBe(200);
  await page.getByRole('button',{name:'提交并继续'}).click();await expect(page.locator('#form-error')).toContainText('其他成员已更新');await expect(page.getByLabel('受理说明')).toHaveValue('本人编辑的受理说明应当保留。');await page.getByRole('button',{name:'已核对最新记录，继续编辑'}).click();await page.getByRole('button',{name:'提交并继续'}).click();await expect(page.locator('.workflow-current b')).toHaveText('当前：原因分析');await expect(page.locator('.timeline')).toContainText('另一会话新增补充记录');
});
